//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Borrowing = new HashSet<Borrowing>();
            this.Borrowing1 = new HashSet<Borrowing>();
            this.Borrowing2 = new HashSet<Borrowing>();
        }
    
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> BookPublishYear { get; set; }
        public string BookLanguage { get; set; }
        public Nullable<int> BookTotalCopy { get; set; }
        public Nullable<int> BookYear { get; set; }
        public Nullable<bool> IsInLibrary { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowing2 { get; set; }
    }
}
