//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public int BorrowingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Book1Id { get; set; }
        public Nullable<int> Book2Id { get; set; }
        public Nullable<int> Book3Id { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> UnitPenalty { get; set; }
        public Nullable<decimal> TotalPenalty { get; set; }
        public Nullable<bool> IsItDelayed { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual Book Book2 { get; set; }
        public virtual User User { get; set; }
    }
}
